### PR TITLE
Fix weapons aim one tick ahead (C++)

### LINKED ISSUE #122: Units constructed earlier than their target aim one tick ahead
This leads to misses, which are particularly noticeable when using beam weapons.

**To Reproduce**
1. Launch a sandbox game with cheats enabled.
2. Enable the `NoDamage` console command.
3. Spawn in a Wagner or a similar unit. Quick units with smaller hitboxes are affected the most.
4. Spawn in 30 Seraphim Tech 2 PDs in a circle.
5. Move the Wagner in circles while the PDs attack it.
6. You will notice the beams overshooting the Wagner.

The bug does not occur when you spawn the PDs first and then the Wagner.

### PR DESCRIPTION
**Pull request by 4z0t**
C++ implementation of https://github.com/FAForever/FA-Binary-Patches/pull/137 and https://github.com/FAForever/FA-Binary-Patches/pull/136 . 

## Summary by CodeRabbit

* **New Features**
  * AI targeting now accounts for target motion when computing aim points and returns precise 2D distance for targeting.
  * Added a reusable 3D vector type with arithmetic, dot/cross, length, safe normalization, and compound assignments.

* **Refactor**
  * Vector math extracted from the core public header into a dedicated math interface for clearer separation and safer usage.

### CODE REVIEW

File: section/Aim/Aim.cxx [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+        void *next_weak_ptr;
+        Vector3f position;
+        int targetBoneIdx;
+        bool targetIsMobile;
+    };
+}
+
+
+// When targeted manually cai_target uses blip and when not - unit's entity
+SHARED __thiscall bool CheckNeedAddEntityVelocity(Moho::CAiTarget *cai_target)
```
Comment (lL1l1) [inline section/Aim/Aim.cxx]: I don't think SHARED needs to be here?

Comment (lL1l1) [inline section/Aim/Aim.cxx:20]: I don't think SHARED needs to be here

**Review by lL1l1 — APPROVED** [review]
Works in testing.

>  Using this to test: https://github.com/lL1l1/fa/tree/test%2Faim-fix
> ```
>    CreateUnitAtMouse('url0402', 1,   -0.10,   -5.85,  0.00052) -- ML on the right that is spawned before
>    CreateUnitAtMouse('url0101', 0,    3.62,   12.20,  2.82791) -- target mole
>    CreateUnitAtMouse('url0402', 1,   -3.52,   -6.35, -0.01520) -- ML on the left that is spawned after
> ```
> In normal game the monkeylord spawned after easily misses when the mole is running somewhat perpendicular. This happens at short (~5-40) and long range (100+), and when idle and when on an attack command.

In patch the Monkeylord spawned after doesn't miss easily and the beams from both look to be aiming at the same point (using `dbg_CollisionBeam` `dbg c` console commands). It works for both attack tasks (attack order, patrol, attack move, assist ground) and idle attacking.

Both ML can inconsistently miss if the mole is at short range and running perpendicular, but I think it's caused by something other than the aim manipulator's aim combined with the mole's small hitbox and high speed. They don't miss when trying to hit a Mantis, so for the vast majority of situations it works.
I noticed the ML spawned before the mole slightly wiggles its aim when the mole comes to a stop. I guess it adds velocity, but engine moves mole by velocity - deceleration.

I didn't test local multiplayer but I don't see anything complex to desync with.

Didn't test vs air units. I know they are especially problematic, but that's probably just because of their high speed making the bug especially obvious.

**Comment by Garanas** [comment]
If this truly fixes the bug at the root then perhaps we should soon revert the changes that were made in Lua to counteract this bug. There are various pull requests that increase the size of various hit boxes (especially tech 1 units and air units) and/or simplify the target bones (on naval units, for example) to reduce the impact of this fundamental bug. These can now be reverted, making micro more rewarding (smaller hitbox = easier to evade things) and the simulation feel more alive (actually using target bones so that not all units aim for the center). 

Great work to all who are involved!

**Comment by 4z0t** [comment]
@BlackYps @Garanas do we merge this? Strogoo and I approve that one :D

**Comment by lL1l1** [comment]
> I didn't test local multiplayer but I don't see anything complex to desync with.

Tested local multiplayer and nothing particularly happened.

> Didn't test vs air units. I know they are especially problematic, but that's probably just because of their high speed making the bug especially obvious.

I tested lightning tanks vs spy planes and strategic bombers and the patch fixes that missing as well. My original comment was based on an experiment I did with trying to make Ythotha's lightning storm target aircraft, where I must've had issues unrelated to aim manipulator ticking.
